trigger:
- main  # Change this to your branch name

jobs:
- job: RunAnsibleInContainer
  displayName: "Run Ansible Playbook in Container"
  pool:
    vmImage: ubuntu-latest  # Uses a Microsoft-hosted agent

  container:
    image: demisto/ansible-runner:1.0.0.2568459
    options: --user root  # Ensure we can install dependencies if needed

  steps:
  - checkout: self  # Ensures the repo is checked out inside the container

  - script: |
      ansible --version      
    displayName: "Run Ansible Playbook"
