trigger:
- main  # Adjust based on your branch

pool:
  vmImage: 'ubuntu-latest'  # Or use a self-hosted agent

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    python -m pip install ansible
    python -m pip install azure-mgmt-compute azure-mgmt-network azure-mgmt-keyvault azure-mgmt-storage azure-mgmt-resource azure-mgmt-automation
    python -m pip install azure-keyvault-secrets azure-storage-blob azure-cli azure-identity azure.mgmt.notificationhubs
  displayName: 'Install Ansible & Required Azure SDK'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription'  # Service connection with Workload Identity Federation
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging in using Workload Identity Federation..."
      az account show
      ansible-playbook -vvv  ./playbooks/playbook.yml
  displayName: 'Run Ansible Playbook'
