trigger:
- main  # Change this to your branch name

jobs:
- job: RunAnsibleInContainer
  displayName: "Run Ansible Playbook in Container"
  pool:
    vmImage: ubuntu-latest  # Uses a Microsoft-hosted agent

  container:
    image: demisto/ansible-runner:1.0.0.2568459
    options: --user root  # Ensure we can install dependencies if needed

  steps:
  - checkout: self  # Ensures the repo is checked out inside the container

  - script: |
      ansible --version      
    displayName: "Run Ansible Playbook"

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'azure-wif-connection'  # Use Workload Identity Federation
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az acount show
        ls
    displayName: 'Run Ansible Playbook'

    #ansible-playbook create_rg.yml
