trigger:
- main  # Adjust based on your branch

pool:
  vmImage: 'ubuntu-latest'  # Or use a self-hosted agent

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    pip install ansible[azure] \
      azure-mgmt-resource \
      azure-mgmt-network \
      azure-mgmt-compute \
      azure-mgmt-automation \
      azure-mgmt-storage \
      azure-mgmt-keyvault \
      azure-cli \
      azure-storage-blob \
      azure-identity
  displayName: 'Install Ansible & Azure SDK'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription'  # Service connection with Workload Identity Federation
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging in using Workload Identity Federation..."
      az account show
      ansible-playbook -vvv  ./playbooks/playbook.yml
  displayName: 'Run Ansible Playbook'
